### ISSUE TITLE
Model: Event

### ISSUE THREAD

**Issue by jtalz** [webotech/webo-core#10]
I have some concerns with the following properties: 

startDate, endDate 

I think these need to be in Date format so that I can properly extract the Calendar date, and time range of the event.

**Comment by AsafKaravani** [comment]
What is their current type?

**Comment by jtalz** [comment]
TIME

**Comment by AsafKaravani** [comment]
Are yoy referring to the DB's Event schema or the Client's Event model?

**Comment by jtalz** [comment]
I'm referring to the DB event schema

**Comment by jtalz** [comment]
```
startDate: {
    type: dataTypes.TIME,
    allowNull: true,
  },
  endDate: {
    type: dataTypes.TIME,
    allowNull: true,
  },
```

**Comment by jtalz** [comment]
changed startDate and endDate to type dataTypes.DATE
