### ISSUE TITLE
Model: Course

### ISSUE THREAD

**Issue by jtalz** [webotech/webo-core#11]
Here are my questions about this model: 

**startDate, endDate, recurrence**: if startDate and endDate will represent the time of the class, then what format will recurrence be in? 

**instructorUserId, instagramId**: will the instructor always have a user in the DB? originally i was thinking something along the lines of `instructor: {
    name: string,
    avatar: string,
    media: string,
  },`

(as it exists in the schema)
```
{
  id: {
    type: dataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  startDate: {
    type: dataTypes.TIME,
    allowNull: true,
  },
  endDate: {
    type: dataTypes.TIME,
    allowNull: true,
  },
  recurrence: {
    type: dataTypes.JSON,
    allowNull: true,
  },
  tags: {
    type: dataTypes.JSON,
    allowNull: true,
  },
  title: {
    type: dataTypes.STRING,
  },
  instructorUserId: {
    type: dataTypes.STRING,
    allowNull: true,
  },
  instagramId: {
    type: dataTypes.STRING,
    allowNull: true,
  },
  content: {
    type: dataTypes.STRING,
  },
  createdAt: {
    type: dataTypes.DATE,
  },
  updatedAt: {
    type: dataTypes.DATE,
  },
}
```

**Comment by AsafKaravani** [comment]
I thought about integrating with a recurrence library like this one:
https://www.npmjs.com/package/rrule

It has to get a start and end dates to be used as an anchor and then the recurrence rules are being applied on those.

**Comment by jtalz** [comment]
I'm all for this library but it seems we need to provide more info then just start and end date. We'll need also 

Frequency (weekly/monthly/daily) 
and if applicable 
Byweekday (Monday, Tuesday...) 

So let's agree on define the possibilities here. 
For starters I'm all for this library.
Let's add the following to the schema: 

Freq: "weekly" "monthly" "daily"
Byweekday?: number (0-6) 

What do you think?

**Comment by AsafKaravani** [comment]
Thats why we have the recurrence json but we dont need it currently, it is an upcoming feature

**Comment by jtalz** [comment]
So what is the status quo for this feature?

Also what do we say about the instructor from my first comment here?

**Comment by jtalz** [comment]
Here's the mock I've been using. I think it represents the type of data we might need as an end result. 

```
{
    id: 1,
    name: 'יוגה',
    level: 'מתחילים',
    frequency: 'שיעור שבועי',
    datetime: 'יום א׳ ב–18:00',
    duration: '45 דקות',
    instructor: {
      name: 'לין לאון',
      avatar: '',
      media: 'Yogawithlyn',
    },
    description: 'קורס קצר למתחילים. נעשה כל מיני תרגילים פשוטים. רק תבוא אם קורים לך ג׳וש.',
    link: 'zoom.il/trainin-with-lyn',
    lists: [{ name: 'ציוד נדרש', items: ['מזרן יוגה', 'מגברת קטנה'], }],
  }
```

**Comment by jtalz** [comment]
The one thing I'm not sure if this library supports is something like: 

Mondays at 4pm 
Tuesdays at 10am
Fridays at 3pm

**Comment by jtalz** [comment]
```
{
  name: string,
  level: string,
  recurrence: Partial<Options>,
  instructor: {
    name: string,
    avatar: string,
    media: string,
  },
  description: string,
  link: string,
  lists: [{ name: string, items: string[], }],
  icon?: string;
}
```

**Comment by jtalz** [comment]
this is a test
